#undef TAPPING_TERM
#define TAPPING_TERM 250

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "xdRLY/ZPQLRV"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 4

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

